services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=dev
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=root
      - DB_DATABASE=taskbar_react_app
      - SYNCHRONIZE=true
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: taskbar_react_app
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
